[package]
name = "sb3"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
enum-field-getter = { path = "../enum-field-getter" }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[dev-dependencies]
pretty_assertions = "1.4.1"