cargo build --target=wasm32-unknown-unknown --release
echo running wasm-bindgen...
wasm-bindgen target/wasm32-unknown-unknown/release/hyperquark.wasm --out-dir=js --no-typescript
echo running wasm-opt...
wasm-opt -Oz js/hyperquark_bg.wasm -o js/hyperquark_bg.wasm