[package]
name = "hyperquark"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
enum-field-getter = { path = "enum-field-getter" }
wasm-encoder = "0.25.0"
wasm-bindgen = "0.2.84"
indexmap = { version = "2.0.0", default-features = false }
ordered-float = { version = "3.7.0", features = ["std", "serde"] }

[dev-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = "z"
